run:
  name: ir_datasets testing using hc4_zho_test

documents:
  input:
    format: irds
    lang: zho
    path: hc4/zh/test
    fields: title+text
  process:
    normalize:
      lowercase: true
      report: false
    stem: false
    stopwords: lucene
    strict_check: true
    tokenize: spacy
  output: true

database:
  name: sqlite
  output: true

index:
  name: lucene
  output: true

topics:
  input:
    format: irds
    lang: eng
    source: original
    encoding: utf8
    path: hc4/zh/test
  fields: title

queries:
  output: true
  parse: false
  process:
    normalize:
      lowercase: true
      report: false
    stem: false
    stopwords: lucene
    strict_check: false
    tokenize: spacy
  psq:
    lang: eng
    normalize:
      lowercase: true
      report: false
    path: ./samples/data/eng_zho_transtable_small.dict 
    stem: false
    stopwords: lucene
    threshold: 0.97

retrieve:
  b: 0.4
  fb_docs: 10
  fb_terms: 10
  k1: 0.9
  log_explanations: false
  log_explanations_cutoff: 10
  mu: 1000
  name: bm25
  number: 1000
  original_query_weight: 0.5
  output: retrieve
  parse: false
  psq: true
  rm3: false
  rm3_logging: false

score:
  input:
    format: irds
    path: hc4/zh/test
